### ISSUE TITLE
Insert contact?

### ISSUE THREAD

**Issue by colegleason** [SamyPesse/glass.py#1]
How might I insert a contact using this library? I want to have the user be able to share photos and such with my app.

**Comment by SamyPesse** [comment]
Contacts will not be really hard to add in glass.py using the api (https://developers.google.com/glass/v1/reference/contacts), I will take some times soon to add it.

**List**

``` python
contacts = user.contacts.list()
for contact in user.contacts:
    print "%s : %s" % (contact.get("id"), contact.get("displayName"))
```

**Insert**

``` python
user.contacts.insert(displayName="John Doe", id="johndoe", imageUrls=["http://.....png"])
```

**Comment by SamyPesse** [comment]
Done for the basics (https://github.com/SamyPesse/glass.py#managing-user-contacts)
Let me know if you need anything else or if there is an issue.
