### ISSUE TITLE
Running on Google appengine?

### ISSUE THREAD

**Issue by hello-josh** [SamyPesse/glass.py#3]
Have you tried to run this on google appengine? I'm struggling trying to get it to load properly

**Comment by SamyPesse** [comment]
No I never tried running it on google appengine. What is the error ?

**Comment by hello-josh** [comment]
I am following this guide:
http://f.souza.cc/2010/08/flying-with-flask-on-google-app-engine.html

I have to wrap the Flask app in `run_wsgi_app(app.web)` but when I do I get a 404 on / with no error

**Comment by SamyPesse** [comment]
It depends the example you tried to run but almost all the examples don't define route for root "/", you should define it yourself using the **app.web** (https://github.com/SamyPesse/glass.py#accessing-the-flask-web-server) :

```
@app.web.route("/")
def index():
    return "Welcome on my Glass Application website !"
```

If you want a complete example, take a look at : https://github.com/SamyPesse/glass.py/tree/master/examples/foursquare

**Comment by hello-josh** [comment]
Thanks! I'll give that a try and then make a pull request with a working
appengine example

**Comment by SamyPesse** [comment]
Thank you.

**Comment by hello-josh** [comment]
I see what is happening now. `app.run()` sets up the initial authorize routes and parameters. Since this is running on appengine I cannot call `app.run()` so I have to set the parameters and add the oauth routes manually

``` python
import os
import sys

# add dist to path for buildout-managed dependencies
sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(__file__)), 'dist'))

from google.appengine.ext.webapp.util import run_wsgi_app

import glass
import config

app = glass.Application(
    name=config.appname,
    client_id=config.client_id,
    client_secret=config.client_secret)

app.port = 8765
app.host = 'localhost'
app.secure = False
app.web.add_url_rule('/glass/oauth/authorize', 'oauth_authorize', app._oauth_authorize)
app.web.add_url_rule('/glass/oauth/callback', 'oauth_callback', app._oauth_callback)

@app.subscriptions.login
def login(user):
    #print "user : %s" % user.token
    user.timeline.post(text="Hello World!")


run_wsgi_app(app.web)
```

Once I got this part working, I get errors about the handler functions not returning a response. I am sure this is because of my inexperience with Flask in general and not because of your code.

```
ERROR    2013-09-10 14:46:02,099 app.py:1306] Exception on /glass/oauth/callback [GET]
Traceback (most recent call last):
  File "/Users/Josh/Developer/InstantHunt/glass/app/dist/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Josh/Developer/InstantHunt/glass/app/dist/flask/app.py", line 1361, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/Josh/Developer/InstantHunt/glass/app/dist/flask/app.py", line 1439, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

**Comment by SamyPesse** [comment]
I just push some changes for improving this (91c58e8610f905de057a65718086b56a74e515ea) : 

You can now use with the same arguments that **run** :

```
app.prepare(...)
```

And I correct the error "View function did not return a response" (it was because your app.subscriptions.login doesn't return something, so there is now a correction for this case).

Your code should be now :

```
import os
import sys

# add dist to path for buildout-managed dependencies
sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(__file__)), 'dist'))

from google.appengine.ext.webapp.util import run_wsgi_app

import glass
import config

app = glass.Application(
    name=config.appname,
    client_id=config.client_id,
    client_secret=config.client_secret)

@app.subscriptions.login
def login(user):
    #print "user : %s" % user.token
    user.timeline.post(text="Hello World!")

app.prepare(port=8765)
run_wsgi_app(app.web)
```

**Comment by hello-josh** [comment]
Resolved and example submitted and integrated via #6
