### ISSUE TITLE
Offline access

### ISSUE THREAD

**Issue by hello-josh** [SamyPesse/glass.py#7]
Does this library or any of the examples handle offline access and refresh tokens?

**Comment by SamyPesse** [comment]
Not yet but I can easily added. I'll do this in a few days.

**Comment by hello-josh** [comment]
Thanks!! If you need any help let me know. I'm writing a Glass version of my app so I'll submit any fixes or enhancements back as I come across them

**Comment by SamyPesse** [comment]
I just added the support for offline mode and refresh token (7bb0e541b121f2426a8b04b90d7a1166299d62de), let me know if it works for you.
(https://github.com/SamyPesse/glass.py#store-users-in-a-database)

There is probably some typos in the documentation, sorry for that, I'm french.
